server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: investment-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://mysql:3306/investment_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
  override-with-generic-response: false

  
  default-produces-media-type: application/json

